### PR TITLE
Fix warnings in Shared project

### PR DESCRIPTION
**Pull request by 74nu5**
- Fix warnings in Shared project
- Suppression of older components

### CODE REVIEW

**Comment by 74nu5** [comment]
Tous les warnings StyleCop sont supprimés, il reste 10 warnings lié à la libraire Dotnet.JsonIdentityProvider.

**Comment by wihary** [comment]
Great job on those warning fixes!!!!

However there is few things that does not work with this PR  :

- [ ] Global client size has been increased from 1.48mo to 2.08mo, which is 30% more for client to download, with no immediate outcome
- [ ] Why adding some external package (regarding first point) to do a .ToString() ?
If you really want to use an attribute instead of the name, which is overkill in my opinion, go for it but within the client code not an external libs.

**Review by wihary — COMMENTED** [review]
Great job on those warning fixes!!!!

However there is few things that does not work with this PR  :

- [x] Global client size has been increased from 1.48mo to 2.08mo, which is 30% more for client to download, with no immediate outcome
- [x] Why adding some external package (regarding first point) to do a .ToString() ?
If you really want to use an attribute instead of the name, which is overkill in my opinion, go for it but within the client code not an external libs.

**Comment by 74nu5** [comment]
Thank you for the review,

The three libraries I added are only 61.1KB, however their dependencies add about 350KB.

The biggest dependencies are "Microsoft.Extensions.Configuration.Abstractions (2.1.1)" and "Microsoft.Extensions.Configuration.Json (2.1.1)", and actually we do not need it on the client side.

So I will import the code is not the library.

For ".ToString ()", having enumeration values starting with a lowercase caused StyleCop warnings. One of the ways is to use the attribute "Display", it is already imported on the develop branch, so there will be no addition of dependencies.

**Comment by wihary** [comment]
By fixing the stylecop warning you reordered method by alphabetic order ==> this is not the way I intend to keep track of methods in class.

Please correct this for PR approval

**Review by wihary — CHANGES_REQUESTED** [review]
By fixing the stylecop warning you reordered method by alphabetic order ==> this is not the way I intend to keep track of methods in class.

Please correct this for PR approval

**Review by wihary — DISMISSED** [review]

**Review by wihary — APPROVED** [review]

**Pull request merged**
